import {
  FaTachometerAlt,
  FaUser,
  FaBook,
  FaClipboardList,
  FaCheckCircle,
  FaCalendarAlt,
  FaBell,
  FaEnvelope,
  FaCog,
  FaUsers,
  FaFileAlt,
  FaMoneyCheckAlt,
  FaDollarSign,
  FaFileInvoiceDollar,
  FaChartPie,
} from "react-icons/fa";

export const SideMenu = {
  studentMenu: [
    { name: "Dashboard", icon: <FaTachometerAlt /> },
    { name: "My Profile", icon: <FaUser /> },
    { name: "Courses", icon: <FaBook /> },
    { name: "Assignments", icon: <FaClipboardList /> },
    { name: "Grades", icon: <FaCheckCircle /> },
    { name: "Attendance", icon: <FaCalendarAlt /> },
    { name: "Schedule", icon: <FaCalendarAlt /> },
    { name: "Library", icon: <FaBook /> },
    { name: "Notifications", icon: <FaBell /> },
    { name: "Messages", icon: <FaEnvelope /> },
    { name: "Settings", icon: <FaCog /> },
  ],
  teacherMenu: [
    { name: "Dashboard", icon: <FaTachometerAlt /> },
    { name: "My Profile", icon: <FaUser /> },
    { name: "Courses", icon: <FaBook /> },
    { name: "Manage Assignments", icon: <FaClipboardList /> },
    { name: "Gradebook", icon: <FaCheckCircle /> },
    { name: "Attendance", icon: <FaCalendarAlt /> },
    { name: "Schedule", icon: <FaCalendarAlt /> },
    { name: "Library", icon: <FaBook /> },
    { name: "Notifications", icon: <FaBell /> },
    { name: "Messages", icon: <FaEnvelope /> },
    { name: "Settings", icon: <FaCog /> },
  ],
  staffMenu: [
    { name: "Dashboard", icon: <FaTachometerAlt /> },
    { name: "My Profile", icon: <FaUser /> },
    { name: "Attendance Management", icon: <FaClipboardList /> },
    { name: "Leave Requests", icon: <FaClipboardList /> },
    { name: "Library Management", icon: <FaBook /> },
    { name: "Inventory", icon: <FaClipboardList /> },
    { name: "Notices", icon: <FaBell /> },
    { name: "Messages", icon: <FaEnvelope /> },
    { name: "Settings", icon: <FaCog /> },
  ],
  adminMenu: [
    { name: "Dashboard", icon: <FaTachometerAlt /> },
    { name: "User Management", icon: <FaUsers /> },
    { name: "Course Management", icon: <FaBook /> },
    { name: "Class Schedules", icon: <FaCalendarAlt /> },
    { name: "Attendance", icon: <FaClipboardList /> },
    { name: "Grades", icon: <FaCheckCircle /> },
    { name: "Library Management", icon: <FaBook /> },
    { name: "Reports", icon: <FaFileAlt /> },
    { name: "Notifications", icon: <FaBell /> },
    { name: "Messages", icon: <FaEnvelope /> },
    { name: "Settings", icon: <FaCog /> },
  ],
  financeMenu: [
    { name: "Dashboard", icon: <FaTachometerAlt /> },
    { name: "Student Fees", icon: <FaMoneyCheckAlt /> },
    { name: "Salaries", icon: <FaDollarSign /> },
    { name: "Expenses", icon: <FaFileInvoiceDollar /> },
    { name: "Financial Reports", icon: <FaChartPie /> },
    { name: "Budgeting", icon: <FaChartPie /> },
    { name: "Invoices", icon: <FaFileInvoiceDollar /> },
    { name: "Notifications", icon: <FaBell /> },
    { name: "Messages", icon: <FaEnvelope /> },
    { name: "Settings", icon: <FaCog /> },
  ],
  adminSubMenu: [
    { name: "Dashboard", icon: <FaTachometerAlt /> },
    { name: "User Management", icon: <FaUsers /> },
    { name: "Course Management", icon: <FaBook /> },
    { name: "Class Schedules", icon: <FaCalendarAlt /> },
    { name: "Attendance", icon: <FaClipboardList /> },
    { name: "Grades", icon: <FaCheckCircle /> },
    { name: "Library Management", icon: <FaBook /> },
    { name: "Reports", icon: <FaFileAlt /> },
    { name: "Notifications", icon: <FaBell /> },
    { name: "Messages", icon: <FaEnvelope /> },
    { name: "Settings", icon: <FaCog /> },
  ],
};
